<?php

namespace Faveo\Installer;

use Illuminate\Support\ServiceProvider;

class FaveoInstallerServiceProvider extends  ServiceProvider
{
    public function boot(){
        $this->loadRoutesFrom(__DIR__.'/routes/web.php');
        $this->loadViewsFrom(__DIR__.'/resources/views','installer');
        $this->loadMigrationsFrom(__DIR__.'Database/migrations');
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

}
